#!/usr/bin/env bash
#Bash script that displays info about subdomains

dig_domain () {
    domain_info=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tail -1)
    echo "$2 $domain_info" | awk '{print "The subdomain " $1 " is a " $5 " record and points to " $6}'
}
sub_domains=("www" "lb-01" "web-01" "web-02")
if [ -z "$2" ]; then
        for sub_domain in "${sub_domains[@]}"; do
            dig_domain "$1" "$sub_domain"
        done
else
    dig_domain "$1" "$2"
fi
