#!/usr/bin/env bash
#install nginx, redirect and customize 404 page
sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R "$USER":"$USER" /var/www/html
echo "Hello World!" > /var/www/html/index.nginx-debian.html

sudo sed -i 's/listen 80 default_server;/listen 80 default_server;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;/' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo sed -i 's/listen 80 default_server;/listen 80 default_server;\n\terror_page 404 \/404.html;/' /etc/nginx/sites-available/default
sudo sed -i 's/listen 80 default_server;/listen 80 default_server;\n\tadd_header X-Served-By $hostname;/' /etc/nginx/sites-available/default
sudo service nginx reload
