#!/usr/bin/env bash
#install and configure HAproxy
sudo apt-get -y update && sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo cp -a /etc/haproxy/haproxy.cfg{,.original_copy}
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
echo -e "\nfrontend server\n\tbind *:80\n\tmode http\n\tdefault_backend lb-server" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "\nbackend lb-server\n\tbalance roundrobin\n\tserver 125283-web-01 54.82.213.159 check\n\tserver 125283-web-02 54.237.76.79 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
