#!/usr/bin/env bash
#Script generates a MySQL dump and creates a compressed archive out of it

if [[ $1 ]]
then
	date=$(date +%d-%m-%Y)
        mysqldump -u root -p"$1" --all-databases > backup.sql
        gzip -c backup.sql > "$date".tar.gz
fi
