#!/usr/bin/env bash
#Script generates a MySQL dump and creates a compressed archive out of it

if [[ $1 ]]
then
        mysqldump -u root -p"$1" --all-databases > backup.sql
        tar -czvf "$(date +"%d-%m-%Y")".tar.gz backup.sql
fi
