#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd
while IFS= read -r line
do
  user_name=$(echo "$line" | cut -d':' -f1)
  group_id=$(echo "$line" | cut -d':' -f4)
  home_directory=$(echo "$line" | cut -d':' -f6)
  command_or_shell=$(echo "$line" | cut -d':' -f7)
  user_id=$(echo "$line" | cut -d':' -f3)
  password=$(echo "$line" | cut -d':' -f2)
  user_info=$(echo "$line" | cut -d':' -f5)
  printf "The user %s is part of the %s gang, lives in %s and rides %s. %s's place is protected by the passcode %s, more info about the user here: %s\n" "$user_name" "$group_id" "$home_directory" "$command_or_shell" "$user_id" "$password" "$user_info" 
done < /etc/passwd
