#!/usr/bin/env bash
# Configure nginx not to run as root
pkill -f apache2
chmod 644 /etc/nginx/nginx.conf
sed -i "s/#user www-data;/#user www-data;\nuser nginx;/" /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
su nginx -c "service nginx restart"
